#!/usr/bin/env python3
"""Rasterizes printable ASCII from a monospace TTF into an alpha atlas header.

    tools/make_font.py /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf src/ui/FontData.h

The default font is DejaVu Sans Mono (Bitstream Vera license: free to embed
and redistribute).
"""
import sys
from PIL import Image, ImageDraw, ImageFont

SIZE = 20
COLUMNS = 16
FIRST, LAST = 32, 126


def main(ttf, out):
    font = ImageFont.truetype(ttf, SIZE)
    ascent, descent = font.getmetrics()
    cell_w = int(round(font.getlength("M")))
    cell_h = ascent + descent
    count = LAST - FIRST + 1
    rows = (count + COLUMNS - 1) // COLUMNS
    atlas = Image.new("L", (cell_w * COLUMNS, cell_h * rows), 0)
    draw = ImageDraw.Draw(atlas)
    for i, code in enumerate(range(FIRST, LAST + 1)):
        x = (i % COLUMNS) * cell_w
        y = (i // COLUMNS) * cell_h
        draw.text((x, y), chr(code), font=font, fill=255)
    data = atlas.tobytes()
    with open(out, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// Generated by tools/make_font.py from DejaVu Sans Mono (Bitstream Vera\n")
        f.write("// license). Printable ASCII, alpha only, %d columns.\n\n" % COLUMNS)
        f.write("#include <cstdint>\n\n")
        f.write("namespace FontData\n{\n")
        f.write("\tconstexpr int FIRST_CHAR = %d;\n\tconstexpr int LAST_CHAR = %d;\n" % (FIRST, LAST))
        f.write("\tconstexpr int COLUMNS = %d;\n" % COLUMNS)
        f.write("\tconstexpr int CELL_WIDTH = %d;\n\tconstexpr int CELL_HEIGHT = %d;\n\tconstexpr int ASCENT = %d;\n" % (cell_w, cell_h, ascent))
        f.write("\tconstexpr int ATLAS_WIDTH = %d;\n\tconstexpr int ATLAS_HEIGHT = %d;\n" % atlas.size)
        f.write("\tconstexpr uint8_t ALPHA[] = {\n")
        for i in range(0, len(data), 32):
            f.write("\t\t" + ",".join(str(b) for b in data[i:i + 32]) + ",\n")
        f.write("\t};\n}\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
